# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    x86_debug:
      configuration: 'debug'
    x86_release:
      configuration: 'release'
  maxParallel: 2

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  submodules: true

- script: init.bat
  displayName: 'Build solution'

- task: MSBuild@1
  inputs:
    solution: '.build/*.sln'
    configuration: $(configuration)
